#define T_ID       1
#define T_NUMBER   2
#define T_COLEQ    3
#define T_EQ       4
#define T_NOTEQ    5
#define T_LT       6
#define T_GT       7
#define T_LE       8
#define T_GE       9
#define T_PERIOD  10
#define T_SEMIC   11
#define T_COMMA   12
#define T_LPAR    13
#define T_RPAR    14
#define T_PLUS    15
#define T_MINUS   16
#define T_MULTI   17
#define T_DIVIDE  18
#define T_CONST   19
#define T_VAR     20
#define T_FUNC    21
#define T_BEGIN   22
#define T_END     23
#define T_IF      24
#define T_THEN    25
#define T_WHILE   26
#define T_DO      27
#define T_RETURN  28
#define T_WRITE   29
#define T_WRITELN 30
#define T_ODD     31

#define T_WHITESPC 128
#define T_ERROR    129
#define T_EOF      255
